/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalproject;
import java.awt.*;
import java.awt.event.ActionEvent;
import javax.swing.*;
import java.awt.event.ActionListener;

/**
 *
 * @author raghad
 */
public class logout extends javax.swing.JFrame {

    /**
     * Creates new form logout
     */
    public logout() {
        initComponents();
        this.setTitle("Moving Car");
        MovingCar car = new MovingCar();
        
        // Set BorderLayout for the frame
        this.setLayout(new BorderLayout());
        
        // Add the MovingCar panel to the center of the frame
        this.add(car, BorderLayout.CENTER);

        this.setSize(400, 400);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

class MovingCar extends JPanel implements ActionListener {
    private int x = 0; // initial x-coordinate of the car

    public MovingCar() {
        Timer timer = new Timer(10, this); // create a timer with 10ms delay
        timer.start(); // start the timer
    }

    public void paintComponent(Graphics g) {
        super.paintComponent(g);
         // رسم المبنى
        g.setColor(Color.BLUE);
        g.fillRect(50, 50, 300, 200);
 // رسم النوافذ
        g.setColor(Color.WHITE);
        for (int i = 0; i < 4; i++) {
            int x = 70 + i * 70;
            g.fillRect(x, 70, 50, 50);
            g.fillRect(x, 140, 50, 50);
        }
        g.setColor(Color.black);
        for (int i = 0; i < 4; i++) {
            int x = 70 + i * 70;
            g.drawRect(x,70, 53, 53);
            g.drawRect(x, 140, 53, 53);
        }
        // رسم الشارع
        g.setColor(Color.GRAY);
        g.fillRect(0, 300, getWidth(), 100);
        
//        g.setColor(Color.RED);
//        g.fillRect(x, 100, 100, 50); // draw the car
        Font font = new Font("Arial", Font.BOLD, 24); // تعيين الخط وحجمه ونمطه
        g.setFont(font); // تعيين الخط المخصص

        g.drawString("Thank you", x, 40); // رسم النص بالخط المخصص
g.setColor(Color.RED);
        g.fillRect(x, 280, 200, 50);
        g.fillRect(x, 260, 220, 20);
        g.fillRect(x, 240, 120, 20);

        // رسم العجلات
        g.setColor(Color.BLACK);
        g.fillOval(x, 310, 50, 50);
        g.fillOval(x+130, 310, 50, 50);
    }

    public void actionPerformed(ActionEvent e) {
        x++; // move the car to the right
        if (x > getWidth()) {
            x = -100; // reset the x-coordinate when the car goes off the screen
        }
        repaint(); // repaint the panel to update the car's position
    }
}